#alias cat='bat'
#alias ls='ls --color=auto --group-directories-first -h -N'
alias ls='exa --group-directories-first'
alias ll='exa -glsnew'
alias tree='exa -T'
alias la='ls -a'
alias reboot='sudo reboot'
alias poweroff='sudo poweroff'
alias serial='sudo screen /dev/ttyUSB0 115200'
alias ciscoserial='sudo screen /dev/ttyS0 9600,cs8,-ixon,-ixoff'
alias xserial='sudo xterm -e /bin/bash -l -c "sudo screen /dev/ttyUSB0 115200"'
alias virsh='sudo virsh --connect qemu:///system'
alias ps='ps -ef | egrep -v grep | egrep carobb'
alias ccat='source-highlight --out-format=esc -o STDOUT -i'
alias fastboot='sudo fastboot'
alias wgparted='xhost +local:; sudo gparted'
alias reload_waybar='killall -SIGUSR2 waybar'
alias irssi='irssi -n trc0'
